// Ctrl+Shift+P on Windows/Linux and search for "DBML: Open Preview to the Side" for preview.

Project DevFlash {
  database_type: "PostgreSQL"
  Note: "Modèle relationnel de l'application DevFlash"
}

Table Stack {
  stack_name varchar(50) [pk]
  slug varchar(50) [not null, unique]
  created_at timestamp [not null, default: `CURRENT_TIMESTAMP`]
}

Table Category {
  category_name varchar(20) [pk]
  description text [not null]
  created_at timestamp [not null, default: `CURRENT_TIMESTAMP`]
  stack_name varchar(50) [not null]
}

Table Flashcard {
  ref_flashcard varchar(20) [pk]
  title varchar(100) [not null]
  definition text [not null]
  doc_url varchar(255) [not null]
  created_at timestamp [not null, default: `CURRENT_TIMESTAMP`]
  category_name varchar(20) [not null]
}

Table Role {
  role_name varchar(50) [pk]
  created_at timestamp [not null, default: `CURRENT_TIMESTAMP`]
}

Table User_ {
  email varchar(320) [pk]
  username varchar(50) [not null]
  password varchar(255) [not null]
  created_at timestamp [not null, default: `CURRENT_TIMESTAMP`]
  role_name varchar(50) [not null]
}

Table Add_Favorite {
  ref_flashcard varchar(20) [pk]
  email varchar(320) [pk]
}

Table Understand {
  ref_flashcard varchar(20) [pk]
  email varchar(320) [pk]
}


// Relations

Ref: Category.stack_name > Stack.stack_name

Ref: Flashcard.category_name > Category.category_name

Ref: User_.role_name > Role.role_name

Ref: Add_Favorite.ref_flashcard > Flashcard.ref_flashcard
Ref: Add_Favorite.email > User_.email

Ref: Understand.ref_flashcard > Flashcard.ref_flashcard
Ref: Understand.email > User_.email
