// Ctrl+Shift+P on Windows/Linux and search for "DBML: Open Preview to the Side" for preview.

Table Stack {
  stack_name varchar(50) [pk]
  slug varchar(50) [not null, unique]
  created_at datetime [not null]
}

Table Category {
  category_name varchar(20) [pk]
  description text [not null]
  created_at datetime [not null]
  stack_name varchar(50) [not null]
}

Table Flashcard {
  ref_flashcard varchar(20) [pk]
  title varchar(100) [not null]
  definition text [not null]
  doc_url varchar(255) [not null]
  created_at datetime [not null]
  category_name varchar(20) [not null]
}

Table Role {
  role_name varchar(50) [pk]
  created_at datetime [not null]
}

Table User_ {
  email varchar(320) [pk]
  username varchar(50) [not null]
  password varchar(255) [not null]
  created_at datetime [not null]
  role_name varchar(50) [not null]
}

Table Favoriser {
  ref_flashcard varchar(20) [pk]
  email varchar(320) [pk]
}

Table Comprendre {
  ref_flashcard varchar(20) [pk]
  email varchar(320) [pk]
}


// Relations 1:N

Ref: Stack.stack_name < Category.stack_name

Ref: Category.category_name < Flashcard.category_name

Ref: Role.role_name < User_.role_name


// Relations N:N via tables d'association

Ref: User_.email < Favoriser.email

Ref: Flashcard.ref_flashcard < Favoriser.ref_flashcard

Ref: User_.email < Comprendre.email

Ref: Flashcard.ref_flashcard < Comprendre.ref_flashcard

